"""BaZi domain: Day Master, Ten Gods (十神), and Luck Pillars interpretation.

The Day Master (日主) is the stem of the DAY pillar — it represents the Self
in BaZi. All other stems/branches are related to it via the Ten Gods system.

Ten Gods (十神) classify the relationship between any stem and the Day Master:
  - Same element:        Companion (比) — friend/rob-wealth
  - Generated by DM:     Output (食/伤) — eating-god/hurting-officer
  - Generates DM:        Resource (印)  — resource/owl
  - Controls DM:         Power (官/杀)  — officer/killer
  - Controlled by DM:    Wealth (财)   — direct-wealth/indirect-wealth

Each pair of (DM element, polarity-match) maps to one of ten specific gods.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from services.bazi_engine.domain.constants import (
    Element,
    Polarity,
    Stem,
    STEM_ELEMENT,
    STEM_POLARITY,
    STEM_HANZI,
)
from services.bazi_engine.domain.pillars import Pillar


# --------------------------------------------------------------------------- #
# Ten Gods (十神)
# --------------------------------------------------------------------------- #
class TenGod(str, Enum):
    """The ten relationship archetypes in BaZi."""

    # Companions — same element as DM
    FRIEND         = "friend"           # 比肩 — same element, same polarity
    ROB_WEALTH     = "rob_wealth"       # 劫财 — same element, opposite polarity
    # Output — DM generates this element
    EATING_GOD     = "eating_god"       # 食神 — generated, same polarity
    HURTING_OFFICER = "hurting_officer" # 伤官 — generated, opposite polarity
    # Resource — this element generates DM
    DIRECT_RESOURCE = "direct_resource" # 正印 — generates DM, opposite polarity
    INDIRECT_RESOURCE = "indirect_resource"  # 偏印 — generates DM, same polarity
    # Power — this element controls DM
    DIRECT_OFFICER = "direct_officer"   # 正官 — controls DM, opposite polarity
    SEVEN_KILLINGS = "seven_killings"   # 七杀 — controls DM, same polarity
    # Wealth — DM controls this element
    DIRECT_WEALTH  = "direct_wealth"    # 正财 — DM controls, opposite polarity
    INDIRECT_WEALTH = "indirect_wealth" # 偏财 — DM controls, same polarity


def _category_of(dm_element: Element, other_element: Element) -> str:
    """Return the broad category of the relationship DM → other."""
    from services.bazi_engine.domain.constants import generates, controls
    if other_element == dm_element:
        return "companion"
    if generates(dm_element, other_element):       # DM 生 other → output
        return "output"
    if generates(other_element, dm_element):       # other 生 DM → resource
        return "resource"
    if controls(other_element, dm_element):        # other 克 DM → power
        return "power"
    if controls(dm_element, other_element):        # DM 克 other → wealth
        return "wealth"
    raise AssertionError("unreachable")  # pragma: no cover


def ten_god(day_master: Stem, other: Stem) -> TenGod:
    """Classify `other` relative to the Day Master via the Ten Gods system.

    Pure function. Same inputs ⇒ same output.
    """
    dm_el = STEM_ELEMENT[day_master]
    dm_pol = STEM_POLARITY[day_master]
    other_el = STEM_ELEMENT[other]
    other_pol = STEM_POLARITY[other]
    same_polarity = (dm_pol == other_pol)
    cat = _category_of(dm_el, other_el)

    if cat == "companion":
        return TenGod.FRIEND if same_polarity else TenGod.ROB_WEALTH
    if cat == "output":
        return TenGod.EATING_GOD if same_polarity else TenGod.HURTING_OFFICER
    if cat == "resource":
        return TenGod.INDIRECT_RESOURCE if same_polarity else TenGod.DIRECT_RESOURCE
    if cat == "power":
        return TenGod.SEVEN_KILLINGS if same_polarity else TenGod.DIRECT_OFFICER
    # wealth
    return TenGod.INDIRECT_WEALTH if same_polarity else TenGod.DIRECT_WEALTH


# --------------------------------------------------------------------------- #
# Day Master profile
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class DayMasterProfile:
    """High-level profile of the native's Day Master."""

    stem: Stem
    element: Element
    polarity: Polarity
    hanzi: str

    @property
    def label(self) -> str:
        pol = "yang" if self.polarity == Polarity.YANG else "yin"
        return f"{pol}_{self.element.value}"


def day_master_profile(day_pillar: Pillar) -> DayMasterProfile:
    return DayMasterProfile(
        stem=day_pillar.stem,
        element=STEM_ELEMENT[day_pillar.stem],
        polarity=STEM_POLARITY[day_pillar.stem],
        hanzi=STEM_HANZI[day_pillar.stem],
    )


# --------------------------------------------------------------------------- #
# Favorable elements (用神)
# --------------------------------------------------------------------------- #
def favorable_elements(day_master_element: Element) -> tuple[Element, ...]:
    """Fallback heuristic favorable elements (used when no full chart is avail).

    Returns the mother (generates DM) + wealth (DM controls). This is the
    BALANCED-chart default. For strength-aware selection, use
    ``favorable_elements_from_chart`` instead, which applies the traditional
    扶抑 (support/suppress) method. A real BaZi reading overrides both.
    """
    from services.bazi_engine.domain.constants import generates, controls, Element
    mother = next(
        (e for e in Element if generates(e, day_master_element)),
        Element.WATER,
    )
    wealth = next(
        (e for e in Element if controls(day_master_element, e)),
        Element.FIRE,
    )
    return (mother, wealth)


def favorable_elements_from_chart(
    four_pillars: "FourPillars",
) -> tuple[Element, ...]:
    """Strength-aware 用神 selection from the full Four Pillars chart.

    Applies the traditional 扶抑 method: assesses Day Master strength (旺衰)
    via season/roots/allies, then selects favorable elements accordingly —
    support (Resource+Companion) for a weak DM, or drain (Output+Wealth+
    Officer) for a strong DM. This is significantly more accurate than the
    element-only heuristic and matches how a practitioner reads a chart.
    """
    from services.bazi_engine.domain.yong_shen import select_yong_shen
    fp = four_pillars
    yong_shen = select_yong_shen(
        dm_stem=fp.day.stem,
        month_branch=fp.month.branch,
        year_branch=fp.year.branch,
        day_branch=fp.day.branch,
        hour_branch=fp.hour.branch if fp.hour else None,
        year_stem=fp.year.stem,
        hour_stem=fp.hour.stem if fp.hour else None,
    )
    return yong_shen.favorable
