"""Remedies catalog: favorable-element → remedy mapping (REMED-2).

Pure functions, no I/O. Two pieces:
  - favorable_elements(day_master_element) — the 用神 (yong shen) heuristic
    mirrored from bazi_engine: mother element (generates DM) + wealth element
    (DM controls). Advisory; a real reading overrides.
  - remedies_for(element) → the catalog of stones/colors/metals/scents that
    support a given element.

These mappings are the deterministic dev reference. Production keeps the same
shape; a curated catalog (DB-backed, curated by a practitioner) drops in
behind the same function signatures.

Privacy: reasoning strings reference ONLY the Day Master element, never birth
data (date/time/coords). They explain *why* an element is favorable.
"""
from __future__ import annotations

from services.remedies.domain.entities import (
    Element,
    Remedy,
    RemedyType,
)


# --------------------------------------------------------------------------- #
# Favorable elements (用神 heuristic) — mirrors bazi_engine.interpretation
# --------------------------------------------------------------------------- #
# Generating cycle: mother generates child. We invert it: who generates X?
_GENERATED_BY: dict[Element, Element] = {
    # X is generated by mother: mother → X
    Element.WOOD: Element.WATER,    # water generates wood
    Element.FIRE: Element.WOOD,     # wood generates fire
    Element.EARTH: Element.FIRE,    # fire generates earth
    Element.METAL: Element.EARTH,   # earth generates metal
    Element.WATER: Element.METAL,   # metal generates water
}
# Controlling cycle: X controls Y. Wealth = the element the Day Master controls.
_CONTROLS: dict[Element, Element] = {
    Element.WOOD: Element.EARTH,    # wood controls earth
    Element.FIRE: Element.METAL,    # fire controls metal
    Element.EARTH: Element.WATER,   # earth controls water
    Element.METAL: Element.WOOD,    # metal controls wood
    Element.WATER: Element.FIRE,    # water controls fire
}


def favorable_elements(day_master_element: Element) -> tuple[Element, ...]:
    """Advisory favorable elements (用神): mother (resource) + wealth.

    Mother = the element that GENERATES the Day Master (nourishes it).
    Wealth = the element the Day Master CONTROLS (its output/achievement).
    A real BaZi reading may override this heuristic.
    """
    mother = _GENERATED_BY[day_master_element]
    wealth = _CONTROLS[day_master_element]
    # De-dup while preserving order (a balanced DM could theoretically overlap).
    seen: list[Element] = []
    for el in (mother, wealth):
        if el not in seen:
            seen.append(el)
    return tuple(seen)


# --------------------------------------------------------------------------- #
# Element → remedy catalog (REMED-2)
# --------------------------------------------------------------------------- #
_CATALOG: dict[Element, tuple[Remedy, ...]] = {
    Element.WOOD: (
        Remedy(Element.WOOD, RemedyType.STONE, "Green Aventurine",
               "Supports Wood — growth, vitality, and new beginnings."),
        Remedy(Element.WOOD, RemedyType.COLOR, "Green",
               "Green resonates with Wood energy, encouraging renewal."),
        Remedy(Element.WOOD, RemedyType.SCENT, "Eucalyptus",
               "Eucalyptus clears the air and invigorates Wood's upward growth."),
    ),
    Element.FIRE: (
        Remedy(Element.FIRE, RemedyType.STONE, "Carnelian",
               "Kindles Fire — courage, motivation, and creative spark."),
        Remedy(Element.FIRE, RemedyType.COLOR, "Red",
               "Red amplifies Fire's warmth and expressive energy."),
        Remedy(Element.FIRE, RemedyType.SCENT, "Cinnamon",
               "Cinnamon warms and stokes Fire's drive."),
    ),
    Element.EARTH: (
        Remedy(Element.EARTH, RemedyType.STONE, "Tiger's Eye",
               "Grounds Earth — stability, patience, and practical wisdom."),
        Remedy(Element.EARTH, RemedyType.COLOR, "Earthy Yellow",
               "Yellow-brown tones anchor Earth's steady support."),
        Remedy(Element.EARTH, RemedyType.SCENT, "Patchouli",
               "Patchouli roots the spirit in Earth's calm."),
    ),
    Element.METAL: (
        Remedy(Element.METAL, RemedyType.STONE, "Clear Quartz",
               "Clarifies Metal — focus, precision, and discernment."),
        Remedy(Element.METAL, RemedyType.METAL, "Silver",
               "Silver carries Metal's refining, clarifying quality."),
        Remedy(Element.METAL, RemedyType.SCENT, "Peppermint",
               "Peppermint sharpens Metal's mental edge."),
    ),
    Element.WATER: (
        Remedy(Element.WATER, RemedyType.STONE, "Aquamarine",
               "Eases Water — flow, intuition, and emotional calm."),
        Remedy(Element.WATER, RemedyType.COLOR, "Deep Blue",
               "Deep blue deepens Water's reflective wisdom."),
        Remedy(Element.WATER, RemedyType.SCENT, "Sandalwood",
               "Sandalwood soothes and steadies Water's depth."),
    ),
}


def remedies_for(element: Element) -> tuple[Remedy, ...]:
    """Return the catalog remedies for an element (REMED-2)."""
    return _CATALOG.get(element, ())


def build_reasoning(element: Element, day_master_element: Element,
                    lang: str = "en") -> str:
    """Privacy-safe reasoning: references the Day Master element, not birth data.

    Matches the API guide example shape:
      "Компенсирует слабый water по Day Master 甲 Wood"
    """
    el = element.value
    dm = day_master_element.value
    role = "nourishes" if element == favorable_elements(day_master_element)[0] \
        else "balances"
    if lang == "ru":
        return f"Компенсирует и {role} элемент {el} по Day Master ({dm})."
    return f"{role.capitalize()} your {dm} Day Master through the {el} element."
